### ISSUE TITLE
[Consult] how to change aplication icon in runtime 

### ISSUE THREAD

**Issue by QingMings** [edvin/tornadofx#228]
in OSX ,  IDEA choose different files, icon dynamic change;

 in java   
    ` primaryStage.getIcons().add(ImageUtil.getImage(""));`

  but  I want to know how to achieve  at tornadofx

**Comment by edvin** [comment]
You can call `addStageIcon(icon)` at any time :)

**Comment by QingMings** [comment]
It must be added 
         ` primaryStage.icons.clear()`
 before that,
only 
     `addStageIcon(icon)`
not work .

**Comment by edvin** [comment]
That's correct :) Do you feel like we should provide a `changeStageIcon()` function that does this?

**Comment by ronsmits** [comment]
Yes :)

Op wo 11 jan. 2017 12:06 schreef Edvin Syse <notifications@github.com>:

**Comment by edvin** [comment]
OK, I committed `setStageIcon(icon)` now.

**Comment by QingMings** [comment]
Excellent!  :)

**Comment by QingMings** [comment]
I found that when I changed the size of the window, application icon will be very strange, or even disappear,At first I thought it was my icon size was too large, but I changed a icon only 2kb,Problems still exist
![Alt text](http://ww1.sinaimg.cn/large/005yCS4cly1felfv3xb72g30rz0hi1kz)

**Comment by edvin** [comment]
Can you try the same icon in a vanilla JavaFX app to see if this is a JavaFX or TornadoFX issue?
